"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Shell } from "@/components/Shell";
import { StatusBadge } from "@/components/StatusBadge";
import { api, formatDate, formatDuration } from "@/lib/api";
import { Job, JobStatus } from "@/types";

export default function AdminDashboard() {
  const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("");
  function load(search = query, filter = status) { const params = new URLSearchParams(); if (search) params.set("search", search); if (filter) params.set("status", filter); api<{items: Job[]}>(`/admin/jobs?${params}`).then(r => setJobs(r.items)).catch(e => setError(e.message)); }
  useEffect(() => { load("", ""); }, []);
  function submit(e: FormEvent) { e.preventDefault(); load(); }
  const counts = { total: jobs.length, waiting: jobs.filter(j => j.status === "SUBMITTED").length, active: jobs.filter(j => ["PROCESSING", "REVIEW"].includes(j.status)).length, done: jobs.filter(j => j.status === "COMPLETED").length };
  const stats = [{label: "Tổng hồ sơ", value: counts.total}, {label: "Đang chờ", value: counts.waiting}, {label: "Đang xử lý", value: counts.active}, {label: "Đã có kết quả", value: counts.done}];
  return <Shell admin><div className="technical-rule mb-6" /><p className="eyebrow">Bàn điều hành</p><h1 className="page-title mt-2">Kiểm soát<br />hồ sơ</h1><p className="mt-4 max-w-xl text-base text-slate-600">Tìm, phân loại và xử lý toàn bộ lượt tra soát của khách hàng.</p><div className="metric-strip metric-strip-four mt-8 grid grid-cols-2 lg:grid-cols-4">{stats.map(({label, value}) => <div className="border-b border-r border-line p-4 last:border-r-0 lg:border-b-0" key={label}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="display-face mt-2 text-4xl font-bold tabular-nums text-slate-950">{value}</p></div>)}</div>
    <form onSubmit={submit} className="mt-7 grid gap-3 border-b border-slate-400 pb-7 sm:grid-cols-[1fr_240px_auto]"><div><label htmlFor="search">Tìm kiếm</label><input id="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Mã, công trình, khách hàng…" /></div><div><label htmlFor="status">Trạng thái</label><select id="status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Tất cả</option>{["SUBMITTED","PROCESSING","WAITING_FOR_INFO","REVIEW","COMPLETED","FAILED"].map(s => <option key={s}>{s}</option>)}</select></div><button className="btn-primary self-end">Tìm hồ sơ</button></form>
    {error && <p className="error mt-5">{error}</p>}<div className="mt-5 border-t-2 border-slate-950"><div className="hidden grid-cols-[140px_minmax(0,1fr)_minmax(0,1fr)_170px_150px] gap-4 border-b border-line px-4 py-3 text-xs font-bold uppercase tracking-wide text-slate-600 lg:grid"><span>Mã hồ sơ</span><span>Công trình</span><span>Khách hàng</span><span>Trạng thái</span><span>Ngày gửi</span></div>{jobs.map(job => <Link href={`/admin/jobs/${job.job_code}`} key={job.job_code} className="job-row grid gap-2 border-b border-line px-4 py-5 lg:grid-cols-[140px_minmax(0,1fr)_minmax(0,1fr)_170px_150px] lg:items-center"><span className="font-mono text-sm font-bold text-brand">{job.job_code}</span><span className="truncate font-semibold">{job.project_name}</span><span className="truncate text-sm text-slate-600">{job.user?.name}</span><StatusBadge status={job.status as JobStatus} /><span className="text-xs text-slate-600">{formatDate(job.created_at)}<span className="mt-1 block">Tổng: {formatDuration(job.turnaround_seconds)}</span><span className="mt-1 block">AI: {formatDuration(job.ai_processing_seconds == null ? null : job.ai_processing_seconds + (job.current_attempt_seconds || 0))}{!job.ai_timing_complete && job.audit_runs.length > 0 ? " (chưa đủ)" : ""}</span></span></Link>)}{jobs.length === 0 && <p className="p-8 text-center text-sm text-slate-500">Không có hồ sơ phù hợp.</p>}</div>
  </Shell>;
}
